
browser=chrome
baseUrl=https://tutorialsninja.com/demo/
reportPath = reports/extent/
screenshotPath = screenshots/
headless = false
firstName = Ravi Prasad
lastName = Kummari
telephone = 9988779870
email = Raviprasad0909@gmail.com
password = Pass@12345
Wrong_Password = wrong
